name: Update Dashboard List

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  generate_table:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Allow the action to write to the repository


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # If you have any dependencies, install them here
          # pip install -r requirements.txt

      - name: Run the script to generate the dashboard table
        run: python update.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add list.md
          git commit -m "Added New Dash In List" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
